<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-HerickMahteus/blob/main/Pr%C3%A1ticasDeDevops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. Vetor de zeros  _(fácil)_

Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.

In [23]:
import numpy as np

print(np.zeros(10))
print(np.zeros(10).dtype)
print(np.zeros(10).shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
(10,)


### 2. Vetor de uns  _(fácil)_

Crie um array 1D com 10 uns e transforme-o em float64.


In [10]:
import numpy as np

print(np.ones(10, dtype=np.float64))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 3. Sequência 0–9  _(fácil)_

Crie um array com os inteiros de 0 a 9 (inclusive).

In [11]:
import numpy as np

print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


### 4. Matriz 3×3 com 0…8  _(fácil)_

Crie um array 3×3 com os valores 0…8 (reshape).

In [12]:
import numpy as np

print(np.arange(9).reshape(3, 3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 5. Índices não zero  _(fácil)_

Dado o vetor `v = np.array([1,2,0,0,4,0])`, encontre os índices dos elementos não nulos.

In [13]:
import numpy as np

print(np.nonzero(np.array([1, 2, 0, 0, 4, 0])))

(array([0, 1, 4]),)


### 6. Linspace  _(fácil)_

Crie um vetor de 12 pontos igualmente espaçados no intervalo [0, 1].

In [17]:
import numpy as np

print(np.linspace(0, 1, 12))

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


### 7. Identidade 5×5  _(fácil)_

Crie uma matriz identidade de ordem 5.

In [19]:
import numpy as np

print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 8. Aleatórios 3×3×3  _(fácil)_

Gere um array 3×3×3 com valores aleatórios uniformes em [0,1). Use `np.random.default_rng(42)`.


In [22]:
import numpy as np

print(np.random.default_rng(42).random((3, 3, 3)))

[[[0.77395605 0.43887844 0.85859792]
  [0.69736803 0.09417735 0.97562235]
  [0.7611397  0.78606431 0.12811363]]

 [[0.45038594 0.37079802 0.92676499]
  [0.64386512 0.82276161 0.4434142 ]
  [0.22723872 0.55458479 0.06381726]]

 [[0.82763117 0.6316644  0.75808774]
  [0.35452597 0.97069802 0.89312112]
  [0.7783835  0.19463871 0.466721  ]]]


### 9. Min/Max  _(fácil)_

Crie uma matriz 10×10 de aleatórios uniformes e mostre o valor mínimo e máximo.

In [24]:
import numpy as np

random_matrix = np.random.rand(10, 10)
print("Minimum value:", random_matrix.min())
print("Maximum value:", random_matrix.max())

Minimum value: 0.006147144838685392
Maximum value: 0.9884966484180111


### 10. Padronização 1D  _(fácil)_

Dado `x = [1,2,3,4,5]`, crie um array float e normalize para média 0 e desvio 1.

In [25]:
import numpy as np

x = np.array([1, 2, 3, 4, 5], dtype=np.float64)
mean = np.mean(x)
std_dev = np.std(x)
normalized_x = (x - mean) / std_dev
print(normalized_x)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


### 11. Conversão de tipos  _(fácil)_

Converta `np.array([1,2,3])` (int32) para float32 e depois para int64.

In [26]:
import numpy as np

int32_array = np.array([1, 2, 3], dtype=np.int32)
float32_array = int32_array.astype(np.float32)
int64_array = float32_array.astype(np.int64)

print("Original array (int32):", int32_array, int32_array.dtype)
print("Converted to float32:", float32_array, float32_array.dtype)
print("Converted to int64:", int64_array, int64_array.dtype)

Original array (int32): [1 2 3] int32
Converted to float32: [1. 2. 3.] float32
Converted to int64: [1 2 3] int64


### 12. Clipping  _(fácil)_

Dado `a = [2, 5, 7, 1, 9]`, limite os valores ao intervalo [0,5] (valores acima de 5 tornam-se 5).

In [27]:
import numpy as np

a = np.array([2, 5, 7, 1, 9])
clipped_array = np.clip(a, 0, 5)
print(clipped_array)

[2 5 5 1 5]
