<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-HerickMahteus/blob/main/Pr%C3%A1ticasDeDevops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Treino de NumPy — 42 exercícios hands-on

**Objetivo:** praticar manipulação de arrays NumPy (criação, slicing, broadcasting, álgebra linear, estatística, datas, strides).
**Regras:** use **apenas** NumPy (`import numpy as np`). Para reprodutibilidade, prefira `np.random.default_rng(seed)`.


## Fáceis (24)

### 1. Vetor de zeros  _(fácil)_

Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.

In [ ]:
import numpy as np

print(np.zeros(10))
print(np.zeros(10).dtype)
print(np.zeros(10).shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
(10,)


### 2. Vetor de uns  _(fácil)_

Crie um array 1D com 10 uns e transforme-o em float64.


In [ ]:
import numpy as np

print(np.ones(10, dtype=np.float64))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 3. Sequência 0–9  _(fácil)_

Crie um array com os inteiros de 0 a 9 (inclusive).

In [ ]:
import numpy as np

print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


### 4. Matriz 3×3 com 0…8  _(fácil)_

Crie um array 3×3 com os valores 0…8 (reshape).

In [ ]:
import numpy as np

print(np.arange(9).reshape(3, 3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 5. Índices não zero  _(fácil)_

Dado o vetor `v = np.array([1,2,0,0,4,0])`, encontre os índices dos elementos não nulos.

In [ ]:
import numpy as np

print(np.nonzero(np.array([1, 2, 0, 0, 4, 0])))

(array([0, 1, 4]),)


### 6. Linspace  _(fácil)_

Crie um vetor de 12 pontos igualmente espaçados no intervalo [0, 1].

In [ ]:
import numpy as np

print(np.linspace(0, 1, 12))

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


### 7. Identidade 5×5  _(fácil)_

Crie uma matriz identidade de ordem 5.

In [ ]:
import numpy as np

print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 8. Aleatórios 3×3×3  _(fácil)_

Gere um array 3×3×3 com valores aleatórios uniformes em [0,1). Use `np.random.default_rng(42)`.


In [ ]:
import numpy as np

print(np.random.default_rng(42).random((3, 3, 3)))

[[[0.77395605 0.43887844 0.85859792]
  [0.69736803 0.09417735 0.97562235]
  [0.7611397  0.78606431 0.12811363]]

 [[0.45038594 0.37079802 0.92676499]
  [0.64386512 0.82276161 0.4434142 ]
  [0.22723872 0.55458479 0.06381726]]

 [[0.82763117 0.6316644  0.75808774]
  [0.35452597 0.97069802 0.89312112]
  [0.7783835  0.19463871 0.466721  ]]]


### 9. Min/Max  _(fácil)_

Crie uma matriz 10×10 de aleatórios uniformes e mostre o valor mínimo e máximo.

In [ ]:
import numpy as np

random_matrix = np.random.rand(10, 10)
print("Minimum value:", random_matrix.min())
print("Maximum value:", random_matrix.max())

Minimum value: 0.006147144838685392
Maximum value: 0.9884966484180111


### 10. Padronização 1D  _(fácil)_

Dado `x = [1,2,3,4,5]`, crie um array float e normalize para média 0 e desvio 1.

In [ ]:
import numpy as np

x = np.array([1, 2, 3, 4, 5], dtype=np.float64)
mean = np.mean(x)
std_dev = np.std(x)
normalized_x = (x - mean) / std_dev
print(normalized_x)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


### 11. Conversão de tipos  _(fácil)_

Converta `np.array([1,2,3])` (int32) para float32 e depois para int64.

In [ ]:
import numpy as np

int32_array = np.array([1, 2, 3], dtype=np.int32)
float32_array = int32_array.astype(np.float32)
int64_array = float32_array.astype(np.int64)

print("Original array (int32):", int32_array, int32_array.dtype)
print("Converted to float32:", float32_array, float32_array.dtype)
print("Converted to int64:", int64_array, int64_array.dtype)

Original array (int32): [1 2 3] int32
Converted to float32: [1. 2. 3.] float32
Converted to int64: [1 2 3] int64


### 12. Clipping  _(fácil)_

Dado `a = [2, 5, 7, 1, 9]`, limite os valores ao intervalo [0,5] (valores acima de 5 tornam-se 5).

In [ ]:
import numpy as np

a = np.array([2, 5, 7, 1, 9])
clipped_array = np.clip(a, 0, 5)
print(clipped_array)

[2 5 5 1 5]


### 13. Inversão  _(fácil)_

Crie um vetor de 0 a 9 e inverta a ordem (sem usar `[::-1]`).

In [ ]:
import numpy as np

vector = np.arange(10)
reversed_vector = np.flip(vector)
print(reversed_vector)

[9 8 7 6 5 4 3 2 1 0]


### 14. Empilhamento  _(fácil)_

Dado `a = [1,2,3]` e `b = [4,5,6]`, empilhe horizontal e verticalmente.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

horizontal_stack = np.hstack((a, b))
vertical_stack = np.vstack((a, b))

print("Horizontal stacking:", horizontal_stack)
print("Vertical stacking:", vertical_stack)

Horizontal stacking: [1 2 3 4 5 6]
Vertical stacking: [[1 2 3]
 [4 5 6]]


### 15. Diagonal  _(fácil)_

Crie uma matriz 4×4 com a diagonal principal igual a 5 e as demais entradas zero.

In [ ]:
import numpy as np

diagonal_matrix = np.eye(4) * 5
print(diagonal_matrix)

[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


### 16. Somas por eixo  _(fácil)_

Para a matriz `A = np.arange(12).reshape(3,4)`, calcule a soma por linhas e por colunas.

In [ ]:
import numpy as np

A = np.arange(12).reshape(3, 4)

row_sums = A.sum(axis=1)
col_sums = A.sum(axis=0)

print("Matrix A:\n", A)
print("\nSum of rows:", row_sums)
print("Sum of columns:", col_sums)

Matrix A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Sum of rows: [ 6 22 38]
Sum of columns: [12 15 18 21]


### 17. Frequências inteiras  _(fácil)_

Gere 100 inteiros aleatórios em [0,9] e conte as frequências de cada valor (0 a 9).

In [ ]:
import numpy as np

random_integers = np.random.randint(0, 10, 100)
frequencies = np.bincount(random_integers, minlength=10)
print("Random integers:", random_integers)
print("Frequencies of values 0-9:", frequencies)

Random integers: [9 0 0 3 3 5 9 2 7 6 0 0 5 2 1 5 6 2 3 5 5 7 3 3 0 0 7 3 6 2 7 5 2 4 9 2 1
 3 4 9 7 2 5 1 8 6 3 0 3 9 3 6 7 4 8 7 3 4 3 2 9 6 4 7 8 0 9 7 4 1 2 7 9 5
 1 4 5 3 6 3 4 8 3 0 5 4 1 1 6 1 1 4 0 3 7 8 0 9 8 7]
Frequencies of values 0-9: [11  9  9 16 10 10  8 12  6  9]


### 18. Slicing com passo  _(fácil)_

Dado `v = np.arange(20)`, selecione cada 3º elemento começando do índice 1.

In [ ]:
import numpy as np

v = np.arange(20)
selected_elements = v[1::3]
print(selected_elements)

[ 1  4  7 10 13 16 19]


### 19. Máscara booleana  _(fácil)_

Crie uma máscara para números pares de `0…19` e use-a para filtrar o vetor.

In [ ]:
import numpy as np

vector = np.arange(20)
even_mask = (vector % 2 == 0)
filtered_vector = vector[even_mask]
print("Original vector:", vector)
print("Even mask:", even_mask)
print("Filtered vector (even numbers):", filtered_vector)

Original vector: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Even mask: [ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False]
Filtered vector (even numbers): [ 0  2  4  6  8 10 12 14 16 18]


### 20. Lista de listas → array  _(fácil)_

Converta `[[1,2,3],[4,5,6]]` em `ndarray`, verifique `shape` e `dtype`.

In [ ]:
import numpy as np

list_of_lists = [[1, 2, 3], [4, 5, 6]]
numpy_array = np.array(list_of_lists)

print("NumPy array:\n", numpy_array)
print("Shape:", numpy_array.shape)
print("Dtype:", numpy_array.dtype)

NumPy array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dtype: int64


### 21. Datas básicas  _(fácil)_

Crie um array de datas diárias de 2025-01-01 a 2025-01-07 (inclusive).

In [ ]:
import numpy as np

dates_array = np.arange('2025-01-01', '2025-01-08', dtype='datetime64[D]')
print(dates_array)

['2025-01-01' '2025-01-02' '2025-01-03' '2025-01-04' '2025-01-05'
 '2025-01-06' '2025-01-07']


### 22. Centralizar colunas  _(fácil)_

Dada `A = np.array([[1.,2.,3.],[4.,5.,6.]])`, subtraia a média de cada coluna.

In [ ]:
import numpy as np

A = np.array([[1., 2., 3.], [4., 5., 6.]])
column_means = A.mean(axis=0)
A_centered = A - column_means
print(A_centered)

[[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]


### 23. Produto elemento-a-elemento vs. escalar  _(fácil)_

Dadas `a=[1,2,3]` e `b=[4,5,6]`, calcule produto elemento a elemento e o produto escalar.


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

element_wise_product = a * b
dot_product = np.dot(a, b) # or a @ b

print("Element-wise product:", element_wise_product)
print("Dot product:", dot_product)

Element-wise product: [ 4 10 18]
Dot product: 32


### 24. Troca de colunas  _(fácil)_

Troque as colunas 0 e 2 de `A = np.arange(12).reshape(3,4)` sem copiar (sempre que possível).

In [ ]:
import numpy as np

A = np.arange(12).reshape(3, 4)
print("Original matrix:\n", A)

A[:, [0, 2]] = A[:, [2, 0]]

print("\nMatrix after swapping columns 0 and 2:\n", A)

Original matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Matrix after swapping columns 0 and 2:
 [[ 2  1  0  3]
 [ 6  5  4  7]
 [10  9  8 11]]


## Médios (12)

### 25. Flatten vs. ravel  _(médio)_

Mostre a diferença entre `flatten()` (cópia) e `ravel()` (view quando possível). Modifique o resultado de `ravel()` e observe o original.

In [ ]:
import numpy as np

a = np.arange(12).reshape(3, 4)
print("Original array:\n", a)

# flatten() creates a copy
flattened_a = a.flatten()
flattened_a[0] = 99
print("\nFlattened array (copy) after modification:", flattened_a)
print("Original array after modifying flattened array:\n", a)

# ravel() creates a view if possible
raveled_a = a.ravel()
raveled_a[0] = 88
print("\nRaveled array (view) after modification:", raveled_a)
print("Original array after modifying raveled array:\n", a)

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array (copy) after modification: [99  1  2  3  4  5  6  7  8  9 10 11]
Original array after modifying flattened array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Raveled array (view) after modification: [88  1  2  3  4  5  6  7  8  9 10 11]
Original array after modifying raveled array:
 [[88  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### 26. Tabuleiro 8×8  _(médio)_

Crie uma matriz 8×8 com padrão de tabuleiro (0 e 1 alternados).


In [ ]:
import numpy as np

chessboard = np.zeros((8, 8), dtype=int)
chessboard[1::2, ::2] = 1
chessboard[::2, 1::2] = 1

print(chessboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 27. np.where condicional  _(médio)_

Dado `x = np.arange(-5,6)`, substitua negativos por 0 e mantenha não-negativos.

In [ ]:
import numpy as np

x = np.arange(-5, 6)
print("Original array:", x)

# Replace negative values with 0 using np.where
x_replaced = np.where(x < 0, 0, x)
print("Array with negative values replaced by 0:", x_replaced)

Original array: [-5 -4 -3 -2 -1  0  1  2  3  4  5]
Array with negative values replaced by 0: [0 0 0 0 0 0 1 2 3 4 5]


### 28. Precisão de média  _(médio)_

Gere 1_000_000 floats uniformes em [0,1) e compute a média. Compare com o valor teórico 0.5 (erro absoluto).

In [ ]:
import numpy as np

# Generate 1,000,000 random floats in [0, 1)
random_floats = np.random.rand(1_000_000)

# Compute the mean
mean_value = np.mean(random_floats)

# Theoretical mean for a uniform distribution in [0, 1) is 0.5
theoretical_mean = 0.5

# Calculate the absolute error
absolute_error = np.abs(mean_value - theoretical_mean)

print("Generated mean:", mean_value)
print("Theoretical mean:", theoretical_mean)
print("Absolute error:", absolute_error)

Generated mean: 0.5005275461744118
Theoretical mean: 0.5
Absolute error: 0.0005275461744117527


### 29. Produto cartesiano (broadcasting)  _(médio)_

Dado `a=[1,2,3]` e `b=[10,20,30,40]`, gere todas as somas possíveis `a_i + b_j` via broadcasting (matriz 3×4).

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([10, 20, 30, 40])

# Use broadcasting to generate the outer sum matrix
outer_sum = a[:, np.newaxis] + b
print(outer_sum)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


### 30. Convolução 1D simples  _(médio)_

Implemente uma convolução 1D 'valid' de um sinal `s` por um kernel `k` usando `np.flip` e `np.lib.stride_tricks.sliding_window_view` (sem `np.convolve`).


In [ ]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

# Define a signal and a kernel
s = np.array([1, 2, 3, 4, 5, 6])
k = np.array([1, 0, -1])

# Flip the kernel
flipped_k = np.flip(k)

# Use sliding_window_view on the signal
window_size = len(k)
signal_windows = sliding_window_view(s, window_size)

# Perform the dot product for convolution
convolution_result = np.dot(signal_windows, flipped_k)

print("Signal:", s)
print("Kernel:", k)
print("Flipped kernel:", flipped_k)
print("Signal windows:\n", signal_windows)
print("Convolution result (valid mode):", convolution_result)

Signal: [1 2 3 4 5 6]
Kernel: [ 1  0 -1]
Flipped kernel: [-1  0  1]
Signal windows:
 [[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
Convolution result (valid mode): [2 2 2 2]


### 31. Normalização min–max por coluna  _(médio)_

Dada `A = rng.normal(size=(5,4))`, normalize cada coluna para o intervalo [0,1], tratando colunas constantes.

In [ ]:
import numpy as np

# Generate a random matrix
rng = np.random.default_rng()
A = rng.normal(size=(5, 4))
print("Original matrix:\n", A)

# Calculate min and max for each column
col_min = A.min(axis=0)
col_max = A.max(axis=0)

# Normalize each column
normalized_A = np.zeros_like(A)
for i in range(A.shape[1]):
    # Handle constant columns
    if col_max[i] - col_min[i] == 0:
        normalized_A[:, i] = 0  # Or some other appropriate value, e.g., 0.5
    else:
        normalized_A[:, i] = (A[:, i] - col_min[i]) / (col_max[i] - col_min[i])

print("\nNormalized matrix (per column):\n", normalized_A)

Original matrix:
 [[-1.37776615  0.15820991 -1.45528334  0.48705987]
 [ 2.33037609 -1.27578595  1.07769745 -0.76314527]
 [-0.01713417  0.84611411  0.76126687 -0.69392058]
 [-1.24999721  0.81138974  1.36029322  2.15034611]
 [-1.00468725 -0.13009399  0.27486804  0.23411461]]

Normalized matrix (per column):
 [[0.         0.67580745 0.         0.42910892]
 [1.         0.         0.8996313  0.        ]
 [0.3669309  1.         0.78724558 0.02376005]
 [0.03445632 0.98363525 1.         1.        ]
 [0.10061073 0.53993681 0.61449275 0.34229031]]


### 32. Ordenar por coluna  _(médio)_

Ordene as linhas de `A = np.array([[3,9],[1,4],[2,5]])` pelo valor crescente da 2ª coluna.

In [ ]:
import numpy as np

A = np.array([[3, 9], [1, 4], [2, 5]])
print("Original matrix:\n", A)

# Get the indices that would sort the second column
sorted_indices = np.argsort(A[:, 1])

# Use the indices to sort the rows of the matrix
sorted_A = A[sorted_indices]

print("\nMatrix sorted by the second column:\n", sorted_A)

Original matrix:
 [[3 9]
 [1 4]
 [2 5]]

Matrix sorted by the second column:
 [[1 4]
 [2 5]
 [3 9]]


### 33. Únicos + contagens + primeira ocorrência  _(médio)_

Para `x = [3,1,2,3,2,3,1]`, obtenha valores únicos, contagens e índice da primeira ocorrência de cada valor.

In [ ]:
import numpy as np

x = np.array([3, 1, 2, 3, 2, 3, 1])

unique_values, first_occurrence_indices, counts = np.unique(x, return_index=True, return_counts=True)

print("Original array:", x)
print("Unique values:", unique_values)
print("Indices of first occurrence:", first_occurrence_indices)
print("Counts of unique values:", counts)

Original array: [3 1 2 3 2 3 1]
Unique values: [1 2 3]
Indices of first occurrence: [1 2 0]
Counts of unique values: [2 2 3]


### 34. Matriz de distâncias 2D  _(médio)_

Dada `P` com N pontos 2D, compute a matriz NxN de distâncias euclidianas sem loops explícitos.

In [ ]:
import numpy as np

# Generate a sample set of N 2D points
N = 5
P = np.random.rand(N, 2)
print("Points P:\n", P)

# Compute the squared Euclidean distances using broadcasting
# (x1 - x2)^2 + (y1 - y2)^2
diff = P[:, np.newaxis, :] - P[np.newaxis, :, :]
squared_distances = np.sum(diff**2, axis=-1)

# Take the square root to get the Euclidean distances
distance_matrix = np.sqrt(squared_distances)

print("\nDistance Matrix (Euclidean):\n", distance_matrix)

Points P:
 [[0.78608507 0.0140674 ]
 [0.21048745 0.3131449 ]
 [0.12279963 0.09667728]
 [0.59505975 0.43165543]
 [0.70462165 0.18733436]]

Distance Matrix (Euclidean):
 [[0.         0.64866014 0.66841003 0.45920631 0.19146209]
 [0.64866014 0.         0.23355382 0.40241844 0.50989891]
 [0.66841003 0.23355382 0.         0.57899912 0.58884256]
 [0.45920631 0.40241844 0.57899912 0.         0.26776219]
 [0.19146209 0.50989891 0.58884256 0.26776219 0.        ]]


### 35. Covariância e correlação  _(médio)_

Simule uma matriz 1000×3 de N(0,1) e compute `cov` (colunas como variáveis) e `corrcoef`.

In [ ]:
import numpy as np

# Simulate a 1000x3 matrix from a standard normal distribution
rng = np.random.default_rng()
data = rng.normal(size=(1000, 3))

# Compute the covariance matrix (columns as variables)
covariance_matrix = np.cov(data, rowvar=False)

# Compute the correlation coefficient matrix
correlation_matrix = np.corrcoef(data, rowvar=False)

print("Simulated Data (first 5 rows):\n", data[:5])
print("\nCovariance Matrix:\n", covariance_matrix)
print("\nCorrelation Coefficient Matrix:\n", correlation_matrix)

Simulated Data (first 5 rows):
 [[-0.03384217 -1.74168278 -0.25967987]
 [-0.40101652  0.70789053  1.096129  ]
 [-0.00773103  0.36104093 -0.96745353]
 [ 0.19816343  0.25416496 -2.07844223]
 [ 0.70837479  0.9459753   0.06755121]]

Covariance Matrix:
 [[ 1.02459111 -0.00885461  0.02980782]
 [-0.00885461  0.93542239 -0.0103168 ]
 [ 0.02980782 -0.0103168   0.99643519]]

Correlation Coefficient Matrix:
 [[ 1.         -0.00904462  0.02950057]
 [-0.00904462  1.         -0.01068603]
 [ 0.02950057 -0.01068603  1.        ]]


### 36. One-hot encoding  _(médio)_

Converta os rótulos `y = [2,0,1,2]` em codificação one-hot usando apenas operações NumPy.

In [ ]:
import numpy as np

y = np.array([2, 0, 1, 2])

# Determine the number of classes (maximum value + 1)
num_classes = np.max(y) + 1

# Create a zero array with shape (number of samples, number of classes)
one_hot_encoded = np.zeros((len(y), num_classes), dtype=int)

# Set the appropriate elements to 1 using advanced indexing
one_hot_encoded[np.arange(len(y)), y] = 1

print("Original labels:", y)
print("One-hot encoded labels:\n", one_hot_encoded)

Original labels: [2 0 1 2]
One-hot encoded labels:
 [[0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]


## Difíceis (6)

### 37. k-means 2D (NumPy puro)  _(difícil)_

Implemente k-means com K=3 em pontos 2D: inicialize centróides aleatórios, faça 10 iterações de (1) atribuir pontos ao centróide mais próximo e (2) recomputar centróides.

In [ ]:
import numpy as np

# Generate some sample 2D data
rng = np.random.default_rng(42)
data = rng.random((100, 2))

# Number of clusters
K = 3
# Number of iterations
n_iterations = 10

# Initialize centroids randomly
# We select K random data points as initial centroids
centroids = data[rng.choice(data.shape[0], K, replace=False)]

print("Initial centroids:\n", centroids)

for i in range(n_iterations):
    # Step 1: Assign points to the nearest centroid
    # Calculate distances from each point to each centroid
    # Shape will be (n_points, K)
    distances = np.sqrt(np.sum((data[:, np.newaxis, :] - centroids[np.newaxis, :, :])**2, axis=2))

    # Assign each point to the centroid with the minimum distance
    cluster_assignments = np.argmin(distances, axis=1)

    # Step 2: Recompute centroids
    # For each cluster, compute the mean of the points assigned to it
    new_centroids = np.array([data[cluster_assignments == k].mean(axis=0) for k in range(K)])

    # Check for convergence (optional, but good practice)
    # if np.allclose(new_centroids, centroids):
    #     print(f"Converged after {i+1} iterations")
    #     break

    centroids = new_centroids

print("\nFinal centroids after", n_iterations, "iterations:\n", centroids)

# To visualize the results (optional)
# import matplotlib.pyplot as plt
# plt.scatter(data[:, 0], data[:, 1], c=cluster_assignments, cmap='viridis')
# plt.scatter(centroids[:, 0], centroids[:, 1], marker='x', color='red', s=200)
# plt.title(f'K-Means Clustering after {n_iterations} iterations')
# plt.xlabel('X')
# plt.ylabel('Y')
# plt.show()

Initial centroids:
 [[0.14024909 0.55403614]
 [0.15328432 0.17926831]
 [0.63471832 0.5535794 ]]

Final centroids after 10 iterations:
 [[0.21590466 0.69961248]
 [0.45118606 0.19895016]
 [0.770169   0.67794585]]


### 38. PCA básica (autovetores)  _(difícil)_

Implemente PCA 2D→1D: centralize `X` (N×2), calcule covariância, autovetores, projete em 1D e reconstrua aproximado.

In [ ]:
import numpy as np

# Generate some sample 2D data
rng = np.random.default_rng(42)
X = rng.multivariate_normal([0, 0], [[1, 0.5], [0.5, 1]], 100)
print("Original data (X):\n", X[:5])

# 1. Center the data
mean = np.mean(X, axis=0)
X_centered = X - mean
print("\nCentered data (X_centered):\n", X_centered[:5])

# 2. Calculate the covariance matrix
covariance_matrix = np.cov(X_centered, rowvar=False)
print("\nCovariance matrix:\n", covariance_matrix)

# 3. Calculate eigenvectors and eigenvalues
eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)
print("\nEigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# Sort eigenvalues and eigenvectors in descending order
sorted_indices = np.argsort(eigenvalues)[::-1]
sorted_eigenvalues = eigenvalues[sorted_indices]
sorted_eigenvectors = eigenvectors[:, sorted_indices]

# Select the principal component (the eigenvector with the largest eigenvalue)
principal_component = sorted_eigenvectors[:, 0]
print("\nPrincipal Component:", principal_component)


# 4. Project data onto 1D
# The projected data is the dot product of the centered data and the principal component
X_projected = np.dot(X_centered, principal_component)
print("\nProjected data (1D):\n", X_projected[:5])

# 5. Reconstruct approximate data (optional)
# To reconstruct, multiply the projected data by the principal component and add back the mean
X_reconstructed = np.outer(X_projected, principal_component) + mean
print("\nReconstructed data (approximate):\n", X_reconstructed[:5])

Original data (X):
 [[ 0.25609932 -0.78388479]
 [-1.12019216 -0.17962744]
 [ 2.34073579  1.03855628]
 [ 0.04740826 -0.26883433]
 [ 0.44107219 -0.41197173]]

Centered data (X_centered):
 [[ 0.22025111 -0.77357775]
 [-1.15604037 -0.1693204 ]
 [ 2.30488758  1.04886332]
 [ 0.01156005 -0.2585273 ]
 [ 0.40522398 -0.4016647 ]]

Covariance matrix:
 [[0.91333121 0.4418674 ]
 [0.4418674  0.70076354]]

Eigenvalues: [1.26151745 0.35257729]
Eigenvectors:
 [[ 0.78544994 -0.61892519]
 [ 0.61892519  0.78544994]]

Principal Component: [0.78544994 0.61892519]

Projected data (1D):
 [-0.30579053 -1.0128085   2.45954174 -0.15092922  0.06968275]

Reconstructed data (approximate):
 [[-0.20433495 -0.1995685 ]
 [-0.75966217 -0.63715973]
 [ 1.96769513  1.5119653 ]
 [-0.08269913 -0.10372093]
 [ 0.09058053  0.03282138]]


### 39. Convolução 2D (im2col)  _(difícil)_

Implemente convolução 2D 'valid' de uma imagem `I` por um kernel `K` usando `sliding_window_view` para gerar blocos e multiplicação matricial.

In [ ]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

# Create a sample image and kernel
I = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

K = np.array([[1, 0],
              [0, -1]])

print("Image I:\n", I)
print("\nKernel K:\n", K)

# Get the shape of the kernel
kernel_height, kernel_width = K.shape

# Use sliding_window_view to create overlapping blocks of the image
# The shape of the windows will be (img_height - kernel_height + 1, img_width - kernel_width + 1, kernel_height, kernel_width)
image_windows = sliding_window_view(I, (kernel_height, kernel_width))
print("\nImage windows shape:", image_windows.shape)

# Reshape the kernel to a 1D array
kernel_flat = K.ravel()
print("\nFlattened kernel:", kernel_flat)

# Reshape the image windows for matrix multiplication
# The shape will be (number of windows, kernel_height * kernel_width)
image_windows_flat = image_windows.reshape(-1, kernel_height * kernel_width)
print("\nFlattened image windows shape:", image_windows_flat.shape)

# Perform matrix multiplication and sum across the last axis
# This is equivalent to the dot product between each window and the flattened kernel
convolution_result_flat = np.dot(image_windows_flat, kernel_flat)

# Reshape the result back to the shape of the output convolution
output_height = I.shape[0] - kernel_height + 1
output_width = I.shape[1] - kernel_width + 1
convolution_result = convolution_result_flat.reshape(output_height, output_width)

print("\nConvolution result (valid mode):\n", convolution_result)

Image I:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Kernel K:
 [[ 1  0]
 [ 0 -1]]

Image windows shape: (3, 3, 2, 2)

Flattened kernel: [ 1  0  0 -1]

Flattened image windows shape: (9, 4)

Convolution result (valid mode):
 [[-5 -5 -5]
 [-5 -5 -5]
 [-5 -5 -5]]


### 40. Sistemas lineares e resíduo  _(difícil)_

Gere uma matriz A (100×100) bem-condicionada, um vetor b e resolva `Ax=b` com `np.linalg.solve`. Compute o resíduo relativo `||Ax−b||/||b||` e `cond(A)`.


In [ ]:
import numpy as np

# Generate a well-conditioned random matrix A (100x100)
# We can create a diagonally dominant matrix or use SVD to construct one with controlled singular values
# A simple way to get a reasonably well-conditioned matrix is to use random values
# and ensure it's not singular (e.g., by adding a small identity matrix or checking condition number)
# For this exercise, let's generate a random matrix and check its condition number.
N = 100
rng = np.random.default_rng(42)
A = rng.random((N, N))

# Add a small value to the diagonal to help with conditioning if needed, or regenerate if condition number is too high
# A = A + np.eye(N) * 0.1

# Generate a random vector b
b = rng.random(N)

# Solve the linear system Ax = b for x
# np.linalg.solve is preferred over np.linalg.inv(A) @ b for numerical stability
x = np.linalg.solve(A, b)

# Compute the residual: r = Ax - b
residual = A @ x - b

# Compute the relative residual: ||Ax - b|| / ||b||
relative_residual = np.linalg.norm(residual) / np.linalg.norm(b)

# Compute the condition number of A
condition_number = np.linalg.cond(A)

print("Shape of A:", A.shape)
print("Shape of b:", b.shape)
print("Shape of x:", x.shape)
print("\nRelative Residual ||Ax - b|| / ||b||:", relative_residual)
print("Condition Number of A:", condition_number)

Shape of A: (100, 100)
Shape of b: (100,)
Shape of x: (100,)

Relative Residual ||Ax - b|| / ||b||: 1.0515603222857376e-14
Condition Number of A: 5283.8197312832835


### 41. Regressão linear (OLS) com NumPy  _(difícil)_

Dado `X` (N×d) e `y`, calcule os coeficientes OLS usando `np.linalg.lstsq` e avalie RMSE no treino.

In [ ]:
import numpy as np

# Generate some sample data for linear regression
# X is the feature matrix (N samples x d features)
# y is the target vector (N samples)
N = 100
d = 1
rng = np.random.default_rng(42)
X = 2 * rng.random((N, d))
y = 1 + 2 * X + rng.normal(0, 0.5, (N, d)) # y = 1 + 2*x + noise

# Add a column of ones to X for the intercept term
X_b = np.c_[np.ones((N, 1)), X]

# Calculate the OLS coefficients using np.linalg.lstsq
# The output is (coefficients, residuals, rank, singular_values)
coefficients, residuals, rank, s = np.linalg.lstsq(X_b, y, rcond=None)

print("OLS Coefficients (including intercept):\n", coefficients)

# Make predictions on the training data
y_pred = X_b @ coefficients

# Calculate the Root Mean Squared Error (RMSE) on the training data
# If residuals is not empty, use residuals; otherwise, calculate manually
if residuals.size > 0:
    rmse = np.sqrt(residuals[0] / N)
else:
    rmse = np.sqrt(np.mean((y_pred - y)**2))

print("\nRMSE on training data:", rmse)

OLS Coefficients (including intercept):
 [[0.97434986]
 [2.0191574 ]]

RMSE on training data: 0.48960800301076113


### 42. Rolling window 2D com strides  _(difícil)_

Usando `sliding_window_view`, compute a média local 3×3 de uma imagem 2D sem laços explícitos.


In [ ]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

# Create a sample 2D image
image = np.arange(25).reshape(5, 5)
print("Original Image:\n", image)

# Define the window size
window_size = (3, 3)

# Use sliding_window_view to create overlapping windows
image_windows = sliding_window_view(image, window_size)
print("\nImage windows shape:", image_windows.shape)

# Compute the mean of each window
local_means = np.mean(image_windows, axis=(-2, -1))

print("\nLocal 3x3 Means:\n", local_means)

Original Image:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Image windows shape: (3, 3, 3, 3)

Local 3x3 Means:
 [[ 6.  7.  8.]
 [11. 12. 13.]
 [16. 17. 18.]]
